sudo: required
language: generic 
services:
  - docker
before_install:
  - docker build -t jayashree-debug/react -f Dockerfile.dev .

script:
  - docker run -e CI=true jayashree-debug/react npm run test -- --coverage